FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY vite.config.js ./
COPY postcss.config.js ./
COPY tailwind.config.js ./
COPY gi_db_comuni-2026-01-31-6fcd8 ./gi_db_comuni-2026-01-31-6fcd8
COPY index.html ./
COPY public ./public
COPY src ./src
ARG VITE_API_BASE_URL
ARG VITE_USE_MOCKS
ARG VITE_GROQ_API_KEY
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_USE_MOCKS=$VITE_USE_MOCKS
ENV VITE_GROQ_API_KEY=$VITE_GROQ_API_KEY
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
